apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchbase-service-broker-acceptance
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: couchbase-service-broker-acceptance
rules:
- apiGroups:
  - "*"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: couchbase-service-broker-acceptance
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: couchbase-service-broker-acceptance
subjects:
- kind: ServiceAccount
  name: couchbase-service-broker-acceptance
  namespace: default
