# Broker requires roles to perform certain tasks.
# The Broker requires at least permission to get its configuration file.
# The Broker requires permission to create/delete any resource defined
# as a template, as well as any permission granted with templated roles
# or cluster roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: couchbase-service-broker
rules:
- apiGroups:
  - servicebroker.couchbase.com
  resources:
  - servicebrokerconfigs
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  - couchbasebuckets
  - couchbaseephemeralbuckets
  - couchbasememcachedbuckets
  - couchbasereplications
  - couchbaseusers
  - couchbasegroups
  - couchbaseroles
  - couchbaserolebindings
  - couchbasebackups
  - couchbasebackuprestores
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  - nodes
  - pods
  - pods/exec
  - services
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
# The main Broker configuration.  This defines what classes and plans a client
# can see, along with what can be configured.  Templates are bound to a plan and
# are rendered and created when a service instance/binding is created, then cleaned
# up when deleted.
apiVersion: servicebroker.couchbase.com/v1alpha1
kind: ServiceBrokerConfig
metadata:
  name: couchbase-service-broker
spec:
  # Catalog is simply verbatim what will be exposed on GET /v2/catalog
  catalog:
    services:
    - id: 8522e991-07bc-4225-a859-1eec1e333153
      name: couchbase-developer
      description: Couchbase Server developer deployments
      tags:
      - database
      - nosql
      bindable: true
      planUpdatable: false
      plans:
      - id: ec0f2c9b-0277-46d7-985f-ba1fbf3b068d
        name: couchbase-developer-private
        description: Cluster accessible within the Kubernetes cluster
        schemas:
          serviceInstance:
            create:
              parameters:
                $schema: "http://json-schema.org/draft-04/schema#"
                type: object
                required:
                  - password
                properties:
                  password:
                    description: "Administrator password"
                    type: string
                  size:
                    description: "Cluster size"
                    type: number
                    minimum: 3
                    maximum: 9
            update:
              parameters:
                $schema: "http://json-schema.org/draft-04/schema#"
                type: object
                required:
                  - password
                properties:
                  password:
                    description: "Administrator password"
                    type: string
                  size:
                    description: "Cluster size"
                    type: number
                    minimum: 3
                    maximum: 9
  # Templates allow the end user to define anything they want to be created.
  # The parameters if specified define where the source is, either requesst
  # metadata or parameters.  Parameters allow defaults to be specified if
  # the parameter is not defined.  Parameters are applied to the resource one
  # or many times as required.
  templates:
  - name: couchbase-operator-serviceaccount
    singleton: true
    template:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: couchbase-operator
  - name: couchbase-operator-role
    singleton: true
    template:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        creationTimestamp: null
        name: couchbase-operator
      rules:
      - apiGroups:
        - batch
        resources:
        - jobs
        - cronjobs
        verbs:
        - list
        - watch
        - create
        - update
      - apiGroups:
        - couchbase.com
        resources:
        - couchbaseclusters
        verbs:
        - get
        - list
        - watch
        - update
      - apiGroups:
        - couchbase.com
        resources:
        - couchbasebuckets
        - couchbaseephemeralbuckets
        - couchbasememcachedbuckets
        - couchbasereplications
        - couchbaseusers
        - couchbasegroups
        - couchbaseroles
        - couchbaserolebindings
        - couchbasebackups
        verbs:
        - list
        - watch
      - apiGroups:
        - couchbase.com
        resources:
        - couchbasebackuprestores
        verbs:
        - list
        - watch
        - delete
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - create
        - update
      - apiGroups:
        - ""
        resources:
        - pods
        - services
        - persistentvolumeclaims
        verbs:
        - get
        - list
        - watch
        - create
        - update
        - delete
      - apiGroups:
        - ""
        resources:
        - pods/exec
        verbs:
        - create
      - apiGroups:
        - ""
        resources:
        - events
        verbs:
        - list
        - create
        - update
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - get
        - list
        - watch
      - apiGroups:
        - policy
        resources:
        - poddisruptionbudgets
        verbs:
        - get
        - create
        - delete
        - list
        - watch
  - name: couchbase-operator-rolebinding
    singleton: true
    template:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: couchbase-operator
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: couchbase-operator
      subjects:
      - kind: ServiceAccount
        name: couchbase-operator
        namespace: default
  - name: couchbase-operator-deployment
    singleton: true
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: couchbase-operator
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: couchbase-operator
        template:
          metadata:
            labels:
              app: couchbase-operator
          spec:
            containers:
            - name: couchbase-operator
              image: couchbase/operator:2.0.0-beta
              args:
              - --pod-create-timeout=10m
              command:
              - couchbase-operator
              env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              ports:
              - containerPort: 8080
                name: http
              - containerPort: 8383
                name: prometheus
            serviceAccountName: couchbase-operator
  - name: couchbase-admin-secret
    template:
      apiVersion: v1
      kind: Secret
      metadata: {}
      stringData:
        username: Administrator
    parameters:
    - name: name
      source:
        format:
          string: "%v-admin"
          parameters:
          - registry: instance-name
      destinations:
      - path: /metadata/name
    - name: password
      required: true
      source:
        parameter: /password
      destinations:
      - path: /stringData/password
  - name: couchbase-operator-tls-secret
    template:
      apiVersion: v1
      kind: Secret
      metadata: {}
      stringData: {}
    parameters:
    - name: name
      source:
        format:
          string: "%v-operator-tls"
          parameters:
          - registry: instance-name
      destinations:
      - path: /metadata/name
    - name: ca-cert
      source:
        registry: ca-cert
      destinations:
      - path: /stringData/ca.crt
  - name: couchbase-server-tls-secret
    template:
      apiVersion: v1
      kind: Secret
      metadata: {}
      stringData: {}
    parameters:
    - name: name
      source:
        format:
          string: "%v-server-tls"
          parameters:
          - registry: instance-name
      destinations:
      - path: /metadata/name
    - name: server-key
      source:
        registry: server-key
      destinations:
      - path: /stringData/pkey.key
    - name: server-cert
      source:
        registry: server-cert
      destinations:
      - path: /stringData/chain.pem
  - name: selector-snippet
    template:
      matchLabels: {}
    parameters:
    - name: instance-name
      source:
        registry: instance-name
      destinations:
      - path: /matchLabels/cluster
  - name: couchbase-developer-private
    template:
      apiVersion: couchbase.com/v2
      kind: CouchbaseCluster
      metadata: {}
      spec:
        security:
          rbac:
            managed: true
        networking:
          tls:
            static: {}
        buckets:
          managed: true
        servers:
        - name: default
          services:
          - data
          - index
          - query
    parameters:
    - name: name
      source:
        registry: instance-name
      destinations:
      - path: /metadata/name
    - name: admin-secret
      source:
        format:
          string: "%v-admin"
          parameters:
          - registry: instance-name
      destinations:
      - path: /spec/security/adminSecret
    - name: operator-tls-secret
      source:
        format:
          string: "%v-operator-tls"
          parameters:
          - registry: instance-name
      destinations:
      - path: /spec/networking/tls/static/operatorSecret
    - name: server-tls-secret
      source:
        format:
          string: "%v-server-tls"
          parameters:
          - registry: instance-name
      destinations:
      - path: /spec/networking/tls/static/serverSecret
    - name: label-selector
      source:
        template: selector-snippet
      destinations:
      - path: /spec/buckets/selector
      - path: /spec/security/rbac/selector
    - name: image
      source:
        parameter: /image
      default:
        string: couchbase/server:6.5.0
      destinations:
      - path: /spec/image
    - name: size
      source:
        parameter: /size
      default:
        int: 3
      destinations:
      - path: /spec/servers/0/size
  - name: couchbase-bucket
    template:
      apiVersion: couchbase.com/v2
      kind: CouchbaseBucket
      metadata:
        labels: {}
    parameters:
    - name: name
      source:
        registry: binding-name
      destinations:
      - path: /metadata/name
    - name: instance-name
      source:
        registry: instance-name
      destinations:
      - path: /metadata/labels/cluster
  - name: couchbase-user-secret
    template:
      apiVersion: v1
      kind: Secret
      metadata: {}
      data: {}
    parameters:
    - name: name
      source:
        registry: binding-name
      destinations:
      - path: /metadata/name
    - name: password
      source:
        registry: password
      destinations:
      - path: /data/password
  - name: couchbase-user
    template:
      apiVersion: couchbase.com/v2
      kind: CouchbaseUser
      metadata:
        labels: {}
      spec:
        authDomain: local
    parameters:
    - name: name
      source:
        registry: binding-name
      destinations:
      - path: /metadata/name
      - path: /spec/authSecret
    - name: instance-name
      source:
        registry: instance-name
      destinations:
      - path: /metadata/labels/cluster
  - name: couchbase-group
    template:
      apiVersion: couchbase.com/v2
      kind: CouchbaseGroup
      metadata:
        labels: {}
      spec:
        roles:
        - name: bucket_admin
    parameters:
    - name: name
      source:
        registry: binding-name
      destinations:
      - path: /metadata/name
      - path: /spec/roles/0/bucket
    - name: instance-name
      source:
        registry: instance-name
      destinations:
      - path: /metadata/labels/cluster
  - name: couchbase-role-binding
    template:
      apiVersion: couchbase.com/v2
      kind: CouchbaseRoleBinding
      metadata:
        labels: {}
      spec:
        subjects:
        - kind: CouchbaseUser
        roleRef:
          kind: CouchbaseGroup
    parameters:
    - name: name
      source:
        registry: binding-id
      destinations:
      - path: /metadata/name
      - path: /spec/subjects/0/name
      - path: /spec/roleRef/name
    - name: instance-name
      source:
        registry: instance-name
      destinations:
      - path: /metadata/labels/cluster
  - name: credentials
    template: {}
    parameters:
    - name: connection-string
      source:
        format:
          string: couchbases://%v-srv.%v
          parameters:
          - registry: instance-name
          - registry: namespace
      destinations:
      - path: /connection-string
    - name: ca-cert
      source:
        registry: ca-cert
      destinations:
      - path: /ca.pem
    - name: username
      source:
        registry: binding-name
      destinations:
      - path: /username
    - name: password
      source:
        registry: password
      destinations:
      - path: /password
    - name: bucket
      source:
        registry: binding-name
      destinations:
      - path: /bucket
  # Bindings bind templates to service plans.  These allow the specification of
  # exactly what templates are created when a plan is instantiated or bound to.
  bindings:
  - name: couchbase-developer-private
    service: couchbase-developer
    plan: couchbase-developer-private
    serviceInstance:
      # Create any shared parameters or those exposed by the broker API
      # and commit to the registry.
      parameters:
      # Usually we'd generate unique resource names by prefixing the instance UUID
      # with a string to avoid the name starting with a number, however, there is
      # a defect with couchbase server in that it silently doesn't work if the DNS
      # names are "too long", thus it is not standards compliant.  To this end we
      # use a short random ID.
      - name: short-id
        required: true
        source:
          generatePassword:
            length: 8
            dictionary: abcdefghijklmnopqrstuvwxyz0123456789
        destinations:
        - registry: short-id
      - name: instance-name
        required: true
        source:
          format:
            string: instance-%v
            parameters:
            - registry: short-id
        destinations:
        - registry: instance-name
      # Dashboard URL is returned to the client after service instance provisioning
      # has completed.
      - name: dashboard-url
        required: true
        source:
          format:
            string: http://%v.%v:8091
            parameters:
            - registry: instance-name
            - registry: namespace
        destinations:
        - registry: dashboard-url
      # Bootstrap a CA.
      - name: ca-key
        required: true
        source:
          generateKey:
            type: RSA
            encoding: PKCS8
            bits: 2048
        destinations:
        - registry: ca-key
      - name: ca-cert
        required: true
        source:
          generateCertificate:
            key:
              registry: ca-key
            subject:
              commonName: Couchbase Server CA
            lifetime: 87600h
            usage: CA
        destinations:
        - registry: ca-cert
      # Create the server certificate.
      # Note this must be a pkcs#1 formatted RSA key.
      - name: server-key
        required: true
        source:
          generateKey:
            type: RSA
            encoding: PKCS1
            bits: 2048
        destinations:
        - registry: server-key
      - name: dns-short-srv
        required: true
        source:
          format:
            string: "%v-srv"
            parameters:
            - registry: instance-name
        destinations:
        - registry: dns-short-srv
      - name: dns-namespaced-srv
        required: true
        source:
          format:
            string: "%v-srv.%v"
            parameters:
            - registry: instance-name
            - registry: namespace
        destinations:
        - registry: dns-namespaced-srv
      - name: dns-full-srv
        required: true
        source:
          format:
            string: "%v-srv.%v.svc"
            parameters:
            - registry: instance-name
            - registry: namespace
        destinations:
        - registry: dns-full-srv
      - name: dns-short-wildcard
        required: true
        source:
          format:
            string: "*.%v"
            parameters:
            - registry: instance-name
        destinations:
        - registry: dns-short-wildcard
      - name: dns-namespaced-wildcard
        required: true
        source:
          format:
            string: "*.%v.%v"
            parameters:
            - registry: instance-name
            - registry: namespace
        destinations:
        - registry: dns-namespaced-wildcard
      - name: dns-full-wildcard
        required: true
        source:
          format:
            string: "*.%v.%v.svc"
            parameters:
            - registry: instance-name
            - registry: namespace
        destinations:
        - registry: dns-full-wildcard
      - name: dns-localhost
        required: true
        default:
          string: localhost
        destinations:
        - registry: dns-localhost
      - name: server-cert
        required: true
        source:
          generateCertificate:
            key:
              registry: server-key
            subject:
              commonName: Couchbase Server
            lifetime: 8760h
            usage: Server
            alternativeNames:
              dns:
              - registry: dns-short-srv
              - registry: dns-namespaced-srv
              - registry: dns-full-srv
              - registry: dns-short-wildcard
              - registry: dns-namespaced-wildcard
              - registry: dns-full-wildcard
              - registry: dns-localhost
            ca:
              certificate:
                registry: ca-cert
              key:
                registry: ca-key
        destinations:
        - registry: server-cert
      templates:
      - couchbase-operator-serviceaccount
      - couchbase-operator-role
      - couchbase-operator-rolebinding
      - couchbase-operator-deployment
      - couchbase-admin-secret
      - couchbase-operator-tls-secret
      - couchbase-server-tls-secret
      - couchbase-developer-private
    serviceBinding:
      parameters:
      - name: binding-name
        required: true
        source:
          format:
            string: binding-%v
            parameters:
            - registry: binding-id
        destinations:
        - registry: binding-name
      - name: password
        required: true
        source:
          generatePassword:
            length: 32
        destinations:
        - registry: password
      - name: credentials
        required: true
        source:
          template: credentials
        destinations:
        - registry: credentials
      templates:
      - couchbase-bucket
      - couchbase-group
      - couchbase-role-binding
      - couchbase-user-secret
      - couchbase-user
