name: Release
on:
  workflow_call:
  push:
    branches-ignore:
      - "*"
    tags:
      - "*"

# defaults:
#   run:
#     working-directory: ./service-broker

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   path: service-broker
      - name: Configure Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      # The release is triggered by pushing an annotated tag to the repository.
      # First step is to extract the versioning information and make it available
      # for other steps in the build pipeline.
      - name: Constants
        id: constants
        run: |
          VERSION=$(basename ${{ github.ref }})
          APPLICATION=couchbase-service-broker
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "archive-tgz=${APPLICATION}-${VERSION}-1.tar.gz" >> $GITHUB_OUTPUT
          echo "archive-zip=${APPLICATION}-${VERSION}-1.zip" >> $GITHUB_OUTPUT
          echo "archive-deb=${APPLICATION}_${VERSION}-1_amd64.deb" >> $GITHUB_OUTPUT
          echo "archive-rpm=${APPLICATION}-${VERSION}-1.x86_64.rpm" >> $GITHUB_OUTPUT
      # Make the binaries
      - name: Build Binaries
        run: make -e VERSION=${{ steps.constants.outputs.version }}
        #        cd github.com/ElKiwos/service-broker/;
      - uses: actions/upload-artifact@v4
        with:
          name: service-broker-binary-${{ steps.constants.outputs.version }}
          path: build/bin/broker
          retention-days: 10
      # - uses: actions/download-artifact@v4
      #   with:
      #     path: $GITHUB_WORKSPACE/build/bin/broker
      #     name: service-broker-binary-${{ steps.constants.outputs.version }}

      # Create container images
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          context: git
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ steps.constants.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.constants.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.constants.outputs.version }}
          flavor: |
            latest=true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64
          file: "Dockerfile"
